version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdocker
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Nam@15112003
      - MSSQL_PID=Evaluation
    ports:
      - "1432:1433"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redisdocker
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  coffeestore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffeestoreapi
    depends_on:
      - sqlserver
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Nếu bạn dùng Redis trong appsettings.json hoặc cấu hình riêng,
      # có thể thêm dòng dưới để API biết host Redis:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7000:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
